version: "3"
services:
  openbis:
    build: .
    container_name: "openbis"
    environment:
      SERVER_HOST_PORT: "localhost:${OPENBIS_PORT}"
      POSTGRES_PASSWORD: "changeME"
      ADMIN_PASS: ${ADMIN_PASS}
    ports:
      - ${OPENBIS_PORT}:8080
    restart: always
    networks:
      - openbis_net

networks:
  openbis_net:
    name: opnbis_net
    driver: bridge