version: "3"
services:
  openbis:
    #build: .
    container_name: "openbis"
    image: ghcr.io/mat-o-lab/openbismantic:main #will be changed to latest
    env_file: 
      - .env
    environment:
      SERVER_HOST_PORT: "${HOST_NAME}:${OPENBIS_SSL_PORT}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_PASS: ${ADMIN_PASS}
      GROUP_NAME: ${GROUP_NAME}
      GROUP_ID : ${GROUP_ID}

    ports:
      - ${OPENBIS_PORT}:8080
      - ${OPENBIS_SSL_PORT}:443
    restart: always
    networks:
      - openbis_net
    healthcheck:
      test: ["CMD", "curl", "-f","--insecure", "https://${HOST_NAME}:${OPENBIS_SSL_PORT}/openbis"]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 30s
  init_database:
    # build:
    #   context: ./init_database
    #   dockerfile: ./Dockerfile
    container_name: init_database
    image: ghcr.io/mat-o-lab/openbismatic_init:main #will change to latest
    environment:
      SERVER_HOST_PORT: "${HOST_NAME}:${OPENBIS_SSL_PORT}"
      ADMIN_PASS: ${ADMIN_PASS}
    depends_on:
      openbis:
        condition: service_healthy
    restart: "on-failure"
    networks:
      - openbis_net
networks:
  openbis_net:
    name: openbis_net
    driver: bridge
