version: "3"
services:
  openbis:
    build: .
    container_name: "openbis"
    environment:
      SERVER_HOST_PORT: "${HOST_NAME}:${OPENBIS_PORT}"
      POSTGRES_PASSWORD: "changeME"
      ADMIN_PASS: ${ADMIN_PASS}
    ports:
      - ${OPENBIS_PORT}:8080
    restart: always
    networks:
      - openbis_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST_NAME}:${OPENBIS_PORT}/openbis"]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 30s
  init_database:
    build:
      context: ./init_database
      dockerfile: ./Dockerfile
    container_name: init_database
    environment:
      SERVER_HOST_PORT: "${HOST_NAME}:${OPENBIS_PORT}"
      ADMIN_PASS: ${ADMIN_PASS}
    depends_on:
      openbis:
        condition: service_healthy
    restart: "no"
    networks:
      - openbis_net
networks:
  openbis_net:
    name: opnbis_net
    driver: bridge