version: "3"
services:
  nginx:
    image: nginx:1.23
    ports:
      - ${OPENBIS_PORT}:80
      - ${OPENBIS_SSL_PORT}:443
    environment:
      OPENBIS_SSL_PORT: ${OPENBIS_SSL_PORT}
    volumes:
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs
    entrypoint: /entrypoint.sh
    networks:
      - openbis_net
    depends_on:
      - openbis
      - openbismantic_api
  openbis:
    build: .
    # container_name: "openbis"
    image: ghcr.io/mat-o-lab/openbismantic:latest #will be changed to latest
    environment:
      SERVER_HOST_PORT: "${HOST_NAME}:${OPENBIS_SSL_PORT}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ADMIN_PASS: ${ADMIN_PASS}
      OBSERVER_PASS: ${OBSERVER_PASS}
      GROUP_NAME: ${GROUP_NAME}
      GROUP_ID : ${GROUP_ID}
    restart: always
    networks:
      - openbis_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openbis"]
      interval: 15s
      timeout: 10s
      retries: 30
      start_period: 30s
  init_database:
    build:
      context: ./init_database
      dockerfile: ./Dockerfile
    container_name: init_database
    image: ghcr.io/mat-o-lab/openbismantic_init:latest #will change to latest
    environment:
      SERVER_HOST_PORT: "nginx:443"
      ADMIN_PASS: ${ADMIN_PASS}
    depends_on:
      openbis:
        condition: service_healthy
    restart: "on-failure"
    networks:
      - openbis_net
  openbismantic_api:
    build:
      context: ./openbismantic_api
      dockerfile: ./Dockerfile
    container_name: openbismantic_api
    image: ghcr.io/mat-o-lab/openbismantic_api:latest
    volumes:
      - ./openbismantic_api:/src
    environment:
      OPENBIS_URL: "https://nginx:443"
      NO_VERIFY_CERTIFICATES: 1
      BASE_URL: ${OPENBISMANTIC_URL}
    networks:
      - openbis_net
  openbismantic_ui:
    build:
      context: ./openbismantic_ui
      dockerfile: ./Dockerfile
      target: production
    volumes:
      - ./openbismantic_ui:/app
    container_name: openbismantic_ui
    image: ghcr.io/mat-o-lab/openbismantic_ui:latest
    environment:
      OPENBISMANTIC_URL: ${OPENBISMANTIC_URL}
    networks:
      - openbis_net
networks:
  openbis_net:
    name: openbis_net
    driver: bridge
